name: build

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  dists-and-docs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.8' ]

    name: dists & docs (${{ matrix.python-version }}/${{ matrix.language }})
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -U -r requirements.txt
      - name: Build distributions
        run: |
          python ./setup.py sdist bdist_wheel

      - name: Install package
        run: |
          pip install -e .[docs,test,speed]
      - name: Build docs
        shell: bash
        run: |
          cd docs
          sphinx-build -b html -a -n -T -W --keep-going . _build/html
